name: Deploy Reusable Workflow

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Install Render CLI
        run: |
          curl \
            -L "https://github.com/render-oss/cli/releases/download/v${VERSION}/cli_${VERSION}_linux_amd64.zip" \
            -o render.zip
          unzip render.zip
          sudo mv "cli_v${VERSION}" /usr/local/bin/render
        env:
          VERSION: '2.1.4'
      - name: Trigger deploy with Render CLI
        run: |
          render deploys create ${{ secrets.RENDER_SERVICE_ID }} --output json --confirm --wait
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          CI: true
