name: PROD Workflow

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+']

jobs:
  promote:
    name: Promote to Production
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull and retag Docker Image
        run: |
          docker pull ghcr.io/${{ github.repository }}:sha-${{ github.sha }}
          docker tag ghcr.io/${{ github.repository }}:sha-${{ github.sha }} ghcr.io/${{ github.repository }}:${GITHUB_REF#refs/tags/}
          docker tag ghcr.io/${{ github.repository }}:sha-${{ github.sha }} ghcr.io/${{ github.repository }}:prod
          docker push ghcr.io/${{ github.repository }}:${GITHUB_REF#refs/tags/}
          docker push ghcr.io/${{ github.repository }}:prod
  deploy:
    name: Deploy to PROD
    uses: ./.github/workflows/deploy.reusable.yml
    with:
      environment: PROD
    needs: promote
    secrets: inherit
